### PR TITLE
add kernel support for carp to freebsd if needed and do a better job sup...

### PR DESCRIPTION
**Pull request by sethlyons**
...porting carp on freebsd 10+

### CODE REVIEW

**Comment by sethlyons** [comment]
two tests are currently failing, but putting this in now as a placeholder while i fix them in case you want to look over what i've done.  this is similar to what i did in 5fb5b9092d68b4b49148dfb6960ef44b15df5c8e.

**Comment by sethlyons** [comment]
looks like the tests are failing because the entire config hash is getting passed to the values parameters, and lib/puppet_x/bsd/rc_conf.rb:162-186 is trying to set address to 10.0.0.1 255.255.255.0 NONE vhid 1 pass TopSecret carpdev em0 advbase 1 advskew 0".  the stack trace looks like this:
```ruby
1) bsd::network::interface::carp on FreeBSD 10 should allow device name em0_alias0
     Failure/Error: should contain_bsd__network__interface__carp('em0_alias0')
     Puppet::Error:
       Invalid IP "inet 10.0.0.1 255.255.255.0 NONE vhid 1 pass TopSecret carpdev em0 advbase 1 advskew 0" at /home/slyons/projects/puppet-bsd/spec/fixtures/modules/bsd/manifests/network/interface.pp:93 on node mynode.local
     # ./lib/puppet_x/bsd/rc_conf.rb:168:in `block in process_addresses'
     # ./lib/puppet_x/bsd/rc_conf.rb:163:in `each'
     # ./lib/puppet_x/bsd/rc_conf.rb:163:in `process_addresses'
     # ./lib/puppet_x/bsd/rc_conf.rb:127:in `load_hash'
     # ./lib/puppet_x/bsd/rc_conf.rb:16:in `initialize'
     # ./spec/fixtures/modules/bsd/lib/puppet/parser/functions/get_freebsd_rc_conf_shellconfig.rb:15:in `new'
     # ./spec/fixtures/modules/bsd/lib/puppet/parser/functions/get_freebsd_rc_conf_shellconfig.rb:15:in `block in <module:Functions>'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/support.rb:162:in `build_catalog_without_cache'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/support.rb:171:in `build_catalog'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/support.rb:21:in `load_catalogue'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/example/define_example_group.rb:7:in `catalogue'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/support.rb:7:in `block in subject'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/matchers/create_generic.rb:82:in `call'
     # /home/slyons/.bundler/ruby/2.1/rspec-puppet-8459e1480797/lib/rspec-puppet/matchers/create_generic.rb:82:in `matches?'
     # ./spec/defines/bsd_network_interface_carp_spec.rb:65:in `block (3 levels) in <top (required)>'
```

**Comment by xaque208** [comment]
I can probably look at this on the weekend.

**Comment by xaque208** [comment]
This isn't quite complete.  FreeBSD carp doesn't look to be functional in the module at all.  The function call here at https://github.com/jewjitsu/puppet-bsd/blob/a22f2ff6825eb9a9b2434c74658191771f077f01/manifests/network/interface/carp.pp#L41 is an OpenBSD function.  It looks like I never wrote any further freebsd support beyond the vlan interfaces, but you can see a complete example by looking at the vlan code, as its supported on both platforms, though depth of testing may vary.  For the function logic, you can begin to see the thought process here: https://github.com/jewjitsu/puppet-bsd/blob/a22f2ff6825eb9a9b2434c74658191771f077f01/manifests/network/interface/vlan.pp#L29

If this is something you're willing to work on, that would be excellent, but I'm happy to help however I can.    I just don't both want to be writing the same code. :)

**Comment by sethlyons** [comment]
i'm about to be away for a few weeks.  i'll be more than happy to help test, but i don't think i'll have much time to write it.

**Comment by xaque208** [comment]
I can take a stab at getting initial support going to make it easier to build on top of.  The weather has just been too good here lately.

**Comment by xaque208** [comment]
I'm working on a branch to get the foundation in.  Can you provide the line you expect to live in /etc/rc.conf for a functional carp interface?  I don't think my minimal example is enough, and I'd like sufficient tests in this area.

https://github.com/xaque208/puppet-bsd/pull/55

**Comment by sethlyons** [comment]
the important part is that, beginning with freebsd10, the carp IP is an alias of a physical interface instead of its own interface (e.g., no longer carp0, carp1, etc.).  the current syntax is:
`ifconfig_em0_alias0="vhid 1 advskew 100 pass testpass alias 192.168.1.50/32"`

**Comment by sethlyons** [comment]
Also, I'm happy to help with the tests.

**Comment by xaque208** [comment]
This test is completely faked:

https://github.com/xaque208/puppet-bsd/blob/freebsdcarp/spec/unit/bsd/rc_conf/carp_spec.rb#L67

If you wanted to send a PR to that branch for tests, I'd happily merge them to get the PR in good order before merge to master.  Since we no longer create carp0 devices etc, the logic for the whole chain could use some validation to make sure that we're actually tying to do the correct thing here on physical interfaces.  Since I copied this work from the previous work I did on vlans, and vlans are bound to have an interface name like vlanX, at least some validation would be in order.

**Comment by xaque208** [comment]
Closing as this is pretty old without action.

**Comment by xaque208** [comment]
Apologies for the lack of response here and having bad tests in place.

**Pull request closed without merging**
